spring.datasource.url=jdbc:mysql://localhost:3306/confeitaria_db
spring.datasource.username=root
spring.datasource.password=Senha71882312

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=uma_chave_secreta_super_segura_para_dev_que_deve_ser_trocada_em_producao_1234567890
jwt.expiration=3600000
